### ISSUE TITLE
unknow field scheduler 

### ISSUE THREAD

**Issue by WangXiangUSTC** [WangXiangUSTC/chaos-mesh-actions#10]
get error message:

```log
error: error validating "./chaos.yaml": error validating data: ValidationError(PodChaos.spec): unknown field "scheduler" in org.chaos-mesh.v1alpha1.PodChaos.spec; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by WangXiangUSTC** [comment]
this is because some new update in Chaos Mesh, can fix it by set `CHAOS_MESH_VERSION`: 

```yaml
uses: chaos-mesh/chaos-mesh-actions@v0.5
      env:
        ......
        CHAOS_MESH_VERSION: v1.0.0
```

refer to https://github.com/pingcap/tidb-operator/pull/4011 and https://github.com/pingcap/dm/pull/1743
